package com.jobbrown.common.waterlevels;


/**
* com/jobbrown/common/waterlevels/Alarm.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from waterlevels.idl
* Tuesday, April 28, 2015 10:34:49 PM BST
*/

public final class Alarm implements org.omg.CORBA.portable.IDLEntity
{
  public com.jobbrown.common.waterlevels.Reading reading = null;
  public int sensorID = (int)0;
  public String lms = null;
  public String zone = null;

  public Alarm ()
  {
  } // ctor

  public Alarm (com.jobbrown.common.waterlevels.Reading _reading, int _sensorID, String _lms, String _zone)
  {
    reading = _reading;
    sensorID = _sensorID;
    lms = _lms;
    zone = _zone;
  } // ctor

} // class Alarm
