package com.jobbrown.common.waterlevels;


/**
* com/jobbrown/common/waterlevels/LMSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from waterlevels.idl
* Tuesday, April 28, 2015 7:35:32 PM BST
*/

public interface LMSOperations 
{
  com.jobbrown.common.waterlevels.Sensor findSensorByID (int id);
  boolean registerSensor (String name);
  void raiseAlarm (int raisingSensorID, String zone);
  String[] getLog ();
} // interface LMSOperations
