package com.jobbrown.common.waterlevels;


/**
* com/jobbrown/common/waterlevels/ReadingsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from waterlevels.idl
* Tuesday, April 28, 2015 10:34:49 PM BST
*/

public final class ReadingsHolder implements org.omg.CORBA.portable.Streamable
{
  public com.jobbrown.common.waterlevels.Reading value[] = null;

  public ReadingsHolder ()
  {
  }

  public ReadingsHolder (com.jobbrown.common.waterlevels.Reading[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.jobbrown.common.waterlevels.ReadingsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.jobbrown.common.waterlevels.ReadingsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.jobbrown.common.waterlevels.ReadingsHelper.type ();
  }

}
