package com.jobbrown.common.waterlevels;


/**
* com/jobbrown/common/waterlevels/RMCPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from waterlevels.idl
* Tuesday, April 28, 2015 10:34:49 PM BST
*/

public abstract class RMCPOA extends org.omg.PortableServer.Servant
 implements com.jobbrown.common.waterlevels.RMCOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("registerLMS", new java.lang.Integer (0));
    _methods.put ("raiseAlarm", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // WaterLevels/RMC/registerLMS
       {
         String name = in.read_string ();
         boolean $result = false;
         $result = this.registerLMS (name);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // WaterLevels/RMC/raiseAlarm
       {
         int sensorID = in.read_long ();
         String zone = in.read_string ();
         String lms = in.read_string ();
         com.jobbrown.common.waterlevels.Reading reading = com.jobbrown.common.waterlevels.ReadingHelper.read (in);
         this.raiseAlarm (sensorID, zone, lms, reading);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:WaterLevels/RMC:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public RMC _this() 
  {
    return RMCHelper.narrow(
    super._this_object());
  }

  public RMC _this(org.omg.CORBA.ORB orb) 
  {
    return RMCHelper.narrow(
    super._this_object(orb));
  }


} // class RMCPOA
