package com.jobbrown.common.waterlevels;


/**
* com/jobbrown/common/waterlevels/SensorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from waterlevels.idl
* Tuesday, April 28, 2015 10:34:49 PM BST
*/

public interface SensorOperations 
{
  String[] getLog ();
  com.jobbrown.common.waterlevels.Reading currentReading ();
  boolean isFlooding ();
  void checkAlarmStatus ();
  int id ();
  void id (int newId);
  String name ();
  void name (String newName);
  String zone ();
  void zone (String newZone);
  int waterLevel ();
  void waterLevel (int newWaterLevel);
  int alarmLevel ();
  void alarmLevel (int newAlarmLevel);
  boolean active ();
  void active (boolean newActive);
  com.jobbrown.common.waterlevels.Reading[] readings ();
  void readings (com.jobbrown.common.waterlevels.Reading[] newReadings);
} // interface SensorOperations
