package com.jobbrown.lms.corba;


/**
* com/jobbrown/lms/corba/LMS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lms.idl
* Thursday, April 2, 2015 7:56:26 PM BST
*/

public interface LMS extends LMSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface LMS
