package com.jobbrown.lms.corba;


/**
* com/jobbrown/lms/corba/Reading.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sensor.idl
* Thursday, April 23, 2015 4:35:21 PM BST
*/

public final class Reading implements org.omg.CORBA.portable.IDLEntity
{
  public int time = (int)0;
  public int date = (int)0;
  public int waterLevel = (int)0;
  public int alarmLevel = (int)0;

  public Reading ()
  {
  } // ctor

  public Reading (int _time, int _date, int _waterLevel, int _alarmLevel)
  {
    time = _time;
    date = _date;
    waterLevel = _waterLevel;
    alarmLevel = _alarmLevel;
  } // ctor

} // class Reading
