package com.jobbrown.lms.corba;


/**
* com/jobbrown/lms/corba/Reading.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lms.idl
* Sunday, April 26, 2015 4:50:15 PM BST
*/

public final class Reading implements org.omg.CORBA.portable.IDLEntity
{
  public com.jobbrown.lms.corba.DateTime date = null;
  public int waterLevel = (int)0;
  public int alarmLevel = (int)0;

  public Reading ()
  {
  } // ctor

  public Reading (com.jobbrown.lms.corba.DateTime _date, int _waterLevel, int _alarmLevel)
  {
    date = _date;
    waterLevel = _waterLevel;
    alarmLevel = _alarmLevel;
  } // ctor

} // class Reading
