package com.jobbrown.lms.corba;


/**
* com/jobbrown/lms/corba/RMC.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rmc.idl
* Saturday, April 25, 2015 9:11:47 PM BST
*/

public interface RMC extends RMCOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RMC
