package com.jobbrown.lms.corba;

/**
* com/jobbrown/lms/corba/RMCHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rmc.idl
* Monday, April 27, 2015 3:56:46 PM BST
*/

public final class RMCHolder implements org.omg.CORBA.portable.Streamable
{
  public com.jobbrown.lms.corba.RMC value = null;

  public RMCHolder ()
  {
  }

  public RMCHolder (com.jobbrown.lms.corba.RMC initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.jobbrown.lms.corba.RMCHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.jobbrown.lms.corba.RMCHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.jobbrown.lms.corba.RMCHelper.type ();
  }

}
