package com.jobbrown.lms.corba;


/**
* com/jobbrown/lms/corba/RMCOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rmc.idl
* Monday, April 27, 2015 3:56:46 PM BST
*/

public interface RMCOperations 
{
  boolean registerLMS (String name);
  void raiseAlarm (int sensorID, com.jobbrown.lms.corba.Reading reading);
} // interface RMCOperations
