package com.jobbrown.lms.corba;


/**
* com/jobbrown/lms/corba/RMCOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rmc.idl
* Saturday, April 25, 2015 9:11:47 PM BST
*/

public interface RMCOperations 
{
  void registerLMS (String name);
} // interface RMCOperations
