package com.jobbrown.lms.corba;


/**
* com/jobbrown/lms/corba/RMCOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rmc.idl
* Sunday, April 26, 2015 4:50:15 PM BST
*/

public interface RMCOperations 
{
  boolean registerLMS (String name);
} // interface RMCOperations
