package com.jobbrown.lms.corba;


/**
* com/jobbrown/lms/corba/SensorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sensor.idl
* Thursday, April 2, 2015 7:56:26 PM BST
*/

public interface SensorOperations 
{
  boolean isFlooding ();
  boolean isActive ();
  int getWaterLevel ();
  int getAlarmLevel ();
  void setAlarmLevel (int alarmLevel);
  void setWaterLevel (int waterLevel);
  void setActive (boolean active);
  void checkAlarmStatus ();
} // interface SensorOperations
