package com.jobbrown.lms.corba;


/**
* com/jobbrown/lms/corba/SensorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sensor.idl
* Sunday, April 26, 2015 4:50:15 PM BST
*/

public interface SensorOperations 
{
  com.jobbrown.lms.corba.Reading currentReading ();
  boolean isFlooding ();
  void checkAlarmStatus ();
  int id ();
  void id (int newId);
  String name ();
  void name (String newName);
  String zone ();
  void zone (String newZone);
  int waterLevel ();
  void waterLevel (int newWaterLevel);
  int alarmLevel ();
  void alarmLevel (int newAlarmLevel);
  boolean active ();
  void active (boolean newActive);
  com.jobbrown.lms.corba.DateTime launched ();
  void launched (com.jobbrown.lms.corba.DateTime newLaunched);
  com.jobbrown.lms.corba.Reading[] readings ();
  void readings (com.jobbrown.lms.corba.Reading[] newReadings);
} // interface SensorOperations
