package com.jobbrown.lms.corba;


/**
* com/jobbrown/lms/corba/Sensor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sensor.idl
* Monday, April 27, 2015 3:56:46 PM BST
*/

public interface Sensor extends SensorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Sensor
