package com.jobbrown.lms.corba;


/**
* com/jobbrown/lms/corba/Sensor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sensor.idl
* Sunday, April 26, 2015 4:50:15 PM BST
*/

public interface Sensor extends SensorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Sensor
