package com.jobbrown.lms.corba;


/**
* com/jobbrown/lms/corba/Sensor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sensor.idl
* Thursday, April 2, 2015 7:56:26 PM BST
*/

public interface Sensor extends SensorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Sensor
