package com.jobbrown.lms.corba.SensorPackage;


/**
* com/jobbrown/lms/corba/SensorPackage/readingsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sensor.idl
* Sunday, April 26, 2015 4:34:07 PM BST
*/

public final class readingsHolder implements org.omg.CORBA.portable.Streamable
{
  public com.jobbrown.lms.corba.Reading value[] = null;

  public readingsHolder ()
  {
  }

  public readingsHolder (com.jobbrown.lms.corba.Reading[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.jobbrown.lms.corba.SensorPackage.readingsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.jobbrown.lms.corba.SensorPackage.readingsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.jobbrown.lms.corba.SensorPackage.readingsHelper.type ();
  }

}
