package com.jobbrown.rmc.corba;


/**
* com/jobbrown/rmc/corba/AlarmHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rmc.idl
* Monday, April 27, 2015 3:56:46 PM BST
*/

abstract public class AlarmHelper
{
  private static String  _id = "IDL:RMC/Alarm:1.0";

  public static void insert (org.omg.CORBA.Any a, com.jobbrown.rmc.corba.Alarm that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.jobbrown.rmc.corba.Alarm extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = com.jobbrown.rmc.corba.ReadingHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "reading",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[1] = new org.omg.CORBA.StructMember (
            "sensorID",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (com.jobbrown.rmc.corba.AlarmHelper.id (), "Alarm", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.jobbrown.rmc.corba.Alarm read (org.omg.CORBA.portable.InputStream istream)
  {
    com.jobbrown.rmc.corba.Alarm value = new com.jobbrown.rmc.corba.Alarm ();
    value.reading = com.jobbrown.rmc.corba.ReadingHelper.read (istream);
    value.sensorID = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.jobbrown.rmc.corba.Alarm value)
  {
    com.jobbrown.rmc.corba.ReadingHelper.write (ostream, value.reading);
    ostream.write_long (value.sensorID);
  }

}
