package com.jobbrown.rmc.corba;

/**
* com/jobbrown/rmc/corba/AlarmHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rmc.idl
* Monday, April 27, 2015 3:56:46 PM BST
*/

public final class AlarmHolder implements org.omg.CORBA.portable.Streamable
{
  public com.jobbrown.rmc.corba.Alarm value = null;

  public AlarmHolder ()
  {
  }

  public AlarmHolder (com.jobbrown.rmc.corba.Alarm initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.jobbrown.rmc.corba.AlarmHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.jobbrown.rmc.corba.AlarmHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.jobbrown.rmc.corba.AlarmHelper.type ();
  }

}
