package com.jobbrown.rmc.corba;


/**
* com/jobbrown/rmc/corba/Alarm.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rmc.idl
* Monday, April 27, 2015 3:56:46 PM BST
*/

public final class Alarm implements org.omg.CORBA.portable.IDLEntity
{
  public com.jobbrown.rmc.corba.Reading reading = null;
  public int sensorID = (int)0;

  public Alarm ()
  {
  } // ctor

  public Alarm (com.jobbrown.rmc.corba.Reading _reading, int _sensorID)
  {
    reading = _reading;
    sensorID = _sensorID;
  } // ctor

} // class Alarm
