package com.jobbrown.rmc.corba;


/**
* com/jobbrown/rmc/corba/DateTimeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lms.idl
* Sunday, April 26, 2015 4:50:15 PM BST
*/

abstract public class DateTimeHelper
{
  private static String  _id = "IDL:LMS/DateTime:1.0";

  public static void insert (org.omg.CORBA.Any a, com.jobbrown.rmc.corba.DateTime that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.jobbrown.rmc.corba.DateTime extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [5];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "year",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[1] = new org.omg.CORBA.StructMember (
            "month",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[2] = new org.omg.CORBA.StructMember (
            "day",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[3] = new org.omg.CORBA.StructMember (
            "hours",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[4] = new org.omg.CORBA.StructMember (
            "minutes",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (com.jobbrown.rmc.corba.DateTimeHelper.id (), "DateTime", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.jobbrown.rmc.corba.DateTime read (org.omg.CORBA.portable.InputStream istream)
  {
    com.jobbrown.rmc.corba.DateTime value = new com.jobbrown.rmc.corba.DateTime ();
    value.year = istream.read_long ();
    value.month = istream.read_long ();
    value.day = istream.read_long ();
    value.hours = istream.read_long ();
    value.minutes = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.jobbrown.rmc.corba.DateTime value)
  {
    ostream.write_long (value.year);
    ostream.write_long (value.month);
    ostream.write_long (value.day);
    ostream.write_long (value.hours);
    ostream.write_long (value.minutes);
  }

}
