package com.jobbrown.rmc.corba;


/**
* com/jobbrown/rmc/corba/LMS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lms.idl
* Monday, April 27, 2015 3:56:46 PM BST
*/

public interface LMS extends LMSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface LMS
