package com.jobbrown.rmc.corba;

/**
* com/jobbrown/rmc/corba/LMSHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lms.idl
* Monday, April 27, 2015 3:56:46 PM BST
*/

public final class LMSHolder implements org.omg.CORBA.portable.Streamable
{
  public com.jobbrown.rmc.corba.LMS value = null;

  public LMSHolder ()
  {
  }

  public LMSHolder (com.jobbrown.rmc.corba.LMS initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.jobbrown.rmc.corba.LMSHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.jobbrown.rmc.corba.LMSHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.jobbrown.rmc.corba.LMSHelper.type ();
  }

}
