package com.jobbrown.rmc.corba;


/**
* com/jobbrown/rmc/corba/LMSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lms.idl
* Saturday, April 25, 2015 9:11:47 PM BST
*/

public interface LMSOperations 
{
  void acceptReading (int reading);
  void raiseAlarm (String zone, String raisingSensorName);
  String getSensorName (int ID);
  String getSensorZone (int ID);
  int getSensorAlarmLevel (int ID);
  boolean getSensorActive (int ID);
} // interface LMSOperations
