package com.jobbrown.rmc.corba;


/**
* com/jobbrown/rmc/corba/ReadingsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lms.idl
* Sunday, April 26, 2015 4:50:15 PM BST
*/

public final class ReadingsHolder implements org.omg.CORBA.portable.Streamable
{
  public com.jobbrown.rmc.corba.Reading value[] = null;

  public ReadingsHolder ()
  {
  }

  public ReadingsHolder (com.jobbrown.rmc.corba.Reading[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.jobbrown.rmc.corba.ReadingsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.jobbrown.rmc.corba.ReadingsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.jobbrown.rmc.corba.ReadingsHelper.type ();
  }

}
