package com.jobbrown.rmc.corba;


/**
* com/jobbrown/rmc/corba/RMC.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rmc.idl
* Sunday, April 26, 2015 4:50:15 PM BST
*/

public interface RMC extends RMCOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RMC
