package com.jobbrown.rmc.corba;


/**
* com/jobbrown/rmc/corba/RMC.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rmc.idl
* Monday, April 27, 2015 3:56:46 PM BST
*/

public interface RMC extends RMCOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RMC
