package com.jobbrown.rmc.corba;

/**
* com/jobbrown/rmc/corba/RMCHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rmc.idl
* Sunday, April 26, 2015 4:50:15 PM BST
*/

public final class RMCHolder implements org.omg.CORBA.portable.Streamable
{
  public com.jobbrown.rmc.corba.RMC value = null;

  public RMCHolder ()
  {
  }

  public RMCHolder (com.jobbrown.rmc.corba.RMC initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.jobbrown.rmc.corba.RMCHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.jobbrown.rmc.corba.RMCHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.jobbrown.rmc.corba.RMCHelper.type ();
  }

}
