package com.jobbrown.rmc.corba;


/**
* com/jobbrown/rmc/corba/RMCHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rmc.idl
* Thursday, April 23, 2015 3:58:23 PM BST
*/

abstract public class RMCHelper
{
  private static String  _id = "IDL:RMC/RMC:1.0";

  public static void insert (org.omg.CORBA.Any a, com.jobbrown.rmc.corba.RMC that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.jobbrown.rmc.corba.RMC extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (com.jobbrown.rmc.corba.RMCHelper.id (), "RMC");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.jobbrown.rmc.corba.RMC read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_RMCStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.jobbrown.rmc.corba.RMC value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static com.jobbrown.rmc.corba.RMC narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof com.jobbrown.rmc.corba.RMC)
      return (com.jobbrown.rmc.corba.RMC)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      com.jobbrown.rmc.corba._RMCStub stub = new com.jobbrown.rmc.corba._RMCStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static com.jobbrown.rmc.corba.RMC unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof com.jobbrown.rmc.corba.RMC)
      return (com.jobbrown.rmc.corba.RMC)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      com.jobbrown.rmc.corba._RMCStub stub = new com.jobbrown.rmc.corba._RMCStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
