package com.jobbrown.rmc.corba;


/**
* com/jobbrown/rmc/corba/RMCOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rmc.idl
* Thursday, April 23, 2015 3:58:23 PM BST
*/

public interface RMCOperations 
{
  String getHello ();
} // interface RMCOperations
