package com.jobbrown.rmc.corba;


/**
* com/jobbrown/rmc/corba/RMCPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from rmc.idl
* Thursday, April 23, 2015 3:58:23 PM BST
*/

public abstract class RMCPOA extends org.omg.PortableServer.Servant
 implements com.jobbrown.rmc.corba.RMCOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getHello", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // RMC/RMC/getHello
       {
         String $result = null;
         $result = this.getHello ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:RMC/RMC:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public RMC _this() 
  {
    return RMCHelper.narrow(
    super._this_object());
  }

  public RMC _this(org.omg.CORBA.ORB orb) 
  {
    return RMCHelper.narrow(
    super._this_object(orb));
  }


} // class RMCPOA
