package com.jobbrown.sensor.corba;

/**
* com/jobbrown/sensor/corba/DateTimeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sensor.idl
* Monday, April 27, 2015 3:09:58 PM BST
*/

public final class DateTimeHolder implements org.omg.CORBA.portable.Streamable
{
  public com.jobbrown.sensor.corba.DateTime value = null;

  public DateTimeHolder ()
  {
  }

  public DateTimeHolder (com.jobbrown.sensor.corba.DateTime initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.jobbrown.sensor.corba.DateTimeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.jobbrown.sensor.corba.DateTimeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.jobbrown.sensor.corba.DateTimeHelper.type ();
  }

}
