package com.jobbrown.sensor.corba;


/**
* com/jobbrown/sensor/corba/LMS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lms.idl
* Saturday, April 25, 2015 9:11:47 PM BST
*/

public interface LMS extends LMSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface LMS
