package com.jobbrown.sensor.corba;


/**
* com/jobbrown/sensor/corba/LMSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lms.idl
* Monday, April 27, 2015 3:56:45 PM BST
*/

public interface LMSOperations 
{
  boolean registerSensor (String name);
  void raiseAlarm (String zone, int raisingSensorID);
  String[] getLog ();
} // interface LMSOperations
