package com.jobbrown.sensor.corba;


/**
* com/jobbrown/sensor/corba/LMSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lms.idl
* Thursday, April 2, 2015 7:56:25 PM BST
*/

public interface LMSOperations 
{
  void acceptReading (int reading);
} // interface LMSOperations
