package com.jobbrown.sensor.corba;


/**
* com/jobbrown/sensor/corba/LogHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from lms.idl
* Monday, April 27, 2015 3:56:45 PM BST
*/

public final class LogHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public LogHolder ()
  {
  }

  public LogHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.jobbrown.sensor.corba.LogHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.jobbrown.sensor.corba.LogHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.jobbrown.sensor.corba.LogHelper.type ();
  }

}
