package com.jobbrown.sensor.corba;


/**
* com/jobbrown/sensor/corba/Sensor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sensor.idl
* Saturday, April 25, 2015 9:11:46 PM BST
*/

public interface Sensor extends SensorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Sensor
