package com.jobbrown.sensor.corba;


/**
* com/jobbrown/sensor/corba/Sensor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sensor.idl
* Thursday, April 23, 2015 4:35:21 PM BST
*/

public interface Sensor extends SensorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Sensor
