module Sensor {
	
	interface Sensor {
		boolean isFlooding();

		void checkAlarmStatus();
		
		attribute long id;
		attribute string name;
		attribute string zone;
		attribute long waterLevel;
		attribute long alarmLevel;
		attribute boolean active;
	};
	
};