module Sensor {
	interface Sensor {
		boolean isFlooding();
		boolean isActive();

		long getWaterLevel();
		long getAlarmLevel();

		void setAlarmLevel(in long alarmLevel);
		void setWaterLevel(in long waterLevel);
		void setActive(in boolean active);
		void checkAlarmStatus();
	};
};