module Sensor {

	struct Reading {
		string date;
		long waterLevel;
		long alarmLevel;
	};
	
	typedef sequence<Reading> Readings;
	typedef sequence<string> Log;
	
	interface Sensor {
		Log getLog();
		Reading currentReading();
		boolean isFlooding();
		void checkAlarmStatus();
		
		attribute long id;
		attribute string name;
		attribute string zone;
		attribute long waterLevel;
		attribute long alarmLevel;
		attribute boolean active;
		attribute Readings readings;
	};
	
};